#!/usr/bin/env bash
# Writes deploy/local/simulator/scenario.yml for the Sensor Simulator from the ids the seed left in
# deploy/local/demo-seed.json (run deploy/scripts/seed-demo.sh first). Each demo sensor gets one of
# the five scenarios; the values are academic placeholders and agree with the profiles the seed
# creates (cold rooms 2..8 C, freezer -25..-15 C, fruit store 4..12 C).
#
# Usage: deploy/scripts/generate-simulator-scenario.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SEED="$REPO_ROOT/deploy/local/demo-seed.json"
OUT="$REPO_ROOT/deploy/local/simulator/scenario.yml"

command -v jq >/dev/null || { echo "ERROR: 'jq' is required." >&2; exit 1; }
[[ -f "$SEED" ]] || { echo "ERROR: $SEED not found; run deploy/scripts/seed-demo.sh first." >&2; exit 1; }

id() { jq -er --arg s "$1" '.sensors[] | select(.serialNumber == $s) | .id' "$SEED" \
  || { echo "ERROR: sensor $1 is not in $SEED" >&2; exit 1; }; }

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<YAML
# Generated by deploy/scripts/generate-simulator-scenario.sh; not versioned. Academic placeholders.
coldguard:
  simulator:
    enabled: true
    tick-interval: 1s
    random-seed: 42
    sensors:
      # Vaccine chamber, 2..8 C: normal operation.
      - sensor-id: "$(id SN-VAC-001)"
        baseline: 5.0
        scenario: NOMINAL
      # Vaccine chamber backup probe, 2..8 C: stays out of range, so the incident keeps updating.
      - sensor-id: "$(id SN-VAC-002)"
        baseline: 5.0
        scenario: PERSISTENCE
        breach-value: 11.5
        start-after: 30s
      # Dairy chamber, 2..8 C: two bad readings, then it recovers (never persistent).
      - sensor-id: "$(id SN-LAC-001)"
        baseline: 5.0
        scenario: RECOVERY
        breach-value: 9.5
        start-after: 20s
        breach-readings: 2
      # Fish freezer, -25..-15 C: normal operation.
      - sensor-id: "$(id SN-PES-001)"
        baseline: -20.0
        scenario: NOMINAL
      # Fruit store, 4..12 C: goes silent for five minutes after one minute.
      - sensor-id: "$(id SN-FRU-001)"
        baseline: 8.0
        scenario: CONNECTIVITY_LOSS
        start-after: 60s
        silence-duration: 5m
YAML
echo "Wrote $OUT"
